services:
  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - engine
    networks:
      - scraper-network
  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - scraper-network
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - scraper-network
networks:
  scraper-network:
    driver: bridge